GET http://localhost:8080/login/aplicacoes

GET http://localhost:8080/login/aplicacao/1


POST http://localhost:8080/login/aplicacao
content-type: application/json

{
  "nome": "Beardfy",
  "chaveAutorizacao": ""
}

PUT http://localhost:8080/login/aplicacao/1
content-type: application/json

{
  "nome": "Beardfy",
  "chaveAutorizacao": "teste"
}